language: python
cache: pip
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
install:
    - pip install coveralls coverage
    - pip install zope.testrunner
    - pip install -U -e .[test]
script:
    - coverage run -m zope.testrunner --test-path=src
after_success:
    - coveralls
notifications:
    email: false
